services:
  db:
    image: postgres:latest
    environment:
      # Lê as variáveis do seu arquivo .env
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD} 
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Adiciona a verificação de saúde para o Postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
      
  api:
    build: ./backend
    # Comando corrigido para rodar migrações (alembic) antes de iniciar a API
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      # Lê as variáveis do seu arquivo .env
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db 
    # Espera o 'db' ficar saudável antes de iniciar
    depends_on:
      db:
        condition: service_healthy

#
# O serviço 'pgadmin' foi totalmente removido.
#

volumes:
  postgres_data:
# O volume 'pgadmin_data' foi totalmente removido.