"""feat: adiciona campo quantity ao CartItem

Revision ID: 045432db7322
Revises: 8df6bf545246
Create Date: 2025-10-24 20:51:48.779802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045432db7322'
down_revision: Union[str, Sequence[str], None] = '8df6bf545246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Adicionamos server_default='1' para preencher as linhas existentes.
    op.add_column('cart_items', sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'quantity')
    # ### end Alembic commands ###