"""adiciona foreign key em products.category_id

Revision ID: 652cc11d77c4
Revises: 98bba01dbbe7
Create Date: 2025-10-23 00:14:41.293070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652cc11d77c4'
down_revision: Union[str, Sequence[str], None] = '98bba01dbbe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
