"""feat: adiciona modelos Order e OrderItem

Revision ID: 8df6bf545246
Revises: c11cf2e86610
Create Date: 2025-10-24 20:44:44.102987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df6bf545246'
down_revision: Union[str, Sequence[str], None] = 'c11cf2e86610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
